try adding m1 build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,79 +17,79 @@ env:
   VCONAN_RECIPE_VER: main
 jobs:
 
-  run-build-ubuntu:
-    runs-on: ubuntu-20.04
-    timeout-minutes: 75
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+  # run-build-ubuntu:
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 75
+  #   steps:
+  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 
-      - name: Check out repository code
-        uses: actions/checkout@v3
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v3
 
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
+  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
 
-      - name: Install Conan
-        run: pip3 install conan==${{ env.VCONAN_VER }} --force
+  #     - name: Install Conan
+  #       run: pip3 install conan==${{ env.VCONAN_VER }} --force
 
-      - name: Check out client-cpp code
-        uses: actions/checkout@v3
-        with:
-          repository: opentdf/client-conan
-          ref: ${{ env.VCONAN_RECIPE_VER }}
-          path: client-conan
+  #     - name: Check out client-cpp code
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: opentdf/client-conan
+  #         ref: ${{ env.VCONAN_RECIPE_VER }}
+  #         path: client-conan
 
-      - name: Get client-cpp into conan local cache, built from repo if necessary
-        run: |
-          cd ${{ github.workspace }}
-          cd client-conan
-          conan create recipe/all opentdf-client/${{ env.VCLIENT_CPP_VER }}@ -pr:b=default --build=opentdf-client --build=missing -o opentdf-client:branch_version=${{ env.VCONAN_BRANCH_VERSION }}
+  #     - name: Get client-cpp into conan local cache, built from repo if necessary
+  #       run: |
+  #         cd ${{ github.workspace }}
+  #         cd client-conan
+  #         conan create recipe/all opentdf-client/${{ env.VCLIENT_CPP_VER }}@ -pr:b=default --build=opentdf-client --build=missing -o opentdf-client:branch_version=${{ env.VCONAN_BRANCH_VERSION }}
 
-      - name: Run build
-        run: |
-          cd ${{ github.workspace }}
-          ./build-all.sh
+  #     - name: Run build
+  #       run: |
+  #         cd ${{ github.workspace }}
+  #         ./build-all.sh
 
-      - name: Save artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: build-output-ubuntu
-          retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
-          path: |
-            *.gz
+  #     - name: Save artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: build-output-ubuntu
+  #         retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
+  #         path: |
+  #           *.gz
 
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+  #     - run: echo "🍏 This job's status is ${{ job.status }}."
 
-  run-build-manylinux-aarch64:
-    runs-on: ubuntu-latest
-    needs: run-build-ubuntu
+  # run-build-manylinux-aarch64:
+  #   runs-on: ubuntu-latest
+  #   needs: run-build-ubuntu
 
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+  #   steps:
+  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 
-      - name: Check out repository code
-        uses: actions/checkout@v3
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-        with:
-          platforms: arm64
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v2
+  #       with:
+  #         platforms: arm64
   
-      - name: Build
-        run: ./docker/linux-arm/deploy.sh
+  #     - name: Build
+  #       run: ./docker/linux-arm/deploy.sh
     
-      - name: Save artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: build-output-ubuntu-arm64
-          retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
-          path: |
-            *.gz
+  #     - name: Save artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: build-output-ubuntu-arm64
+  #         retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
+  #         path: |
+  #           *.gz
     
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+  #     - run: echo "🍏 This job's status is ${{ job.status }}."
 
   # run-build-windows:
   #   runs-on: windows-2019
@@ -189,9 +189,9 @@ jobs:
 
   #     - run: echo "🍏 This job's status is ${{ job.status }}."
 
-  run-build-multi:
-    runs-on: ubuntu-20.04
-    timeout-minutes: 75
+  run-build-m1:
+    runs-on: macos-13-xlarge
+    # needs: run-build-ubuntu
     steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
@@ -228,12 +228,32 @@ jobs:
       - name: Save artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: build-output-ubuntu
+          name: build-output-mac-m1
           retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
           path: |
             *.gz
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
+
+  # build-multi:
+  #   needs: [run-build-ubuntu,run-build-manylinux-aarch64,run-build-mac,run-build-m1]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-java@v3
+  #       with:
+  #         # See https://github.com/actions/setup-java#supported-distributions for list
+  #         distribution: 'temurin'
+  #         java-version: '11'
+
+  #     - name: Download artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: build-output-ubuntu
+
+  #     - name: Untar artifact
+  #       run: |
+  #         tar -xzvf *.tar.gz
 
   # test-with-quickstart:
   #   needs: run-build-ubuntu
@@ -294,15 +314,15 @@ jobs:
   #         pwd
   #         tilt ci
 
-  ci:
-    needs:
-      - run-build-ubuntu
-      - run-build-manylinux-aarch64
-      # - run-build-windows
-      # - test-with-quickstart
-      # - run-build-mac
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1
-        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+  # ci:
+  #   needs:
+  #     - run-build-mac
+  #     - run-build-ubuntu
+  #     - run-build-manylinux-aarch64
+  #     - run-build-windows
+  #     - test-with-quickstart
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: exit 1
+  #       if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
