try again

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,79 +17,79 @@ env:
   VCONAN_RECIPE_VER: main
 jobs:
 
-  run-build-ubuntu:
-    runs-on: ubuntu-20.04
-    timeout-minutes: 75
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+  # run-build-ubuntu:
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 75
+  #   steps:
+  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 
-      - name: Check out repository code
-        uses: actions/checkout@v3
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v3
 
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
+  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
 
-      - name: Install Conan
-        run: pip3 install conan==${{ env.VCONAN_VER }} --force
+  #     - name: Install Conan
+  #       run: pip3 install conan==${{ env.VCONAN_VER }} --force
 
-      - name: Check out client-cpp code
-        uses: actions/checkout@v3
-        with:
-          repository: opentdf/client-conan
-          ref: ${{ env.VCONAN_RECIPE_VER }}
-          path: client-conan
+  #     - name: Check out client-cpp code
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: opentdf/client-conan
+  #         ref: ${{ env.VCONAN_RECIPE_VER }}
+  #         path: client-conan
 
-      - name: Get client-cpp into conan local cache, built from repo if necessary
-        run: |
-          cd ${{ github.workspace }}
-          cd client-conan
-          conan create recipe/all opentdf-client/${{ env.VCLIENT_CPP_VER }}@ -pr:b=default --build=opentdf-client --build=missing -o opentdf-client:branch_version=${{ env.VCONAN_BRANCH_VERSION }}
+  #     - name: Get client-cpp into conan local cache, built from repo if necessary
+  #       run: |
+  #         cd ${{ github.workspace }}
+  #         cd client-conan
+  #         conan create recipe/all opentdf-client/${{ env.VCLIENT_CPP_VER }}@ -pr:b=default --build=opentdf-client --build=missing -o opentdf-client:branch_version=${{ env.VCONAN_BRANCH_VERSION }}
 
-      - name: Run build
-        run: |
-          cd ${{ github.workspace }}
-          ./build-all.sh
+  #     - name: Run build
+  #       run: |
+  #         cd ${{ github.workspace }}
+  #         ./build-all.sh
 
-      - name: Save artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: build-output-ubuntu
-          retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
-          path: |
-            *.gz
+  #     - name: Save artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: build-output-ubuntu
+  #         retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
+  #         path: |
+  #           *.gz
 
-      - run: echo "🐧 This job's status is ${{ job.status }}."
+  #     - run: echo "🐧 This job's status is ${{ job.status }}."
 
-  run-build-manylinux-aarch64:
-    runs-on: ubuntu-latest
-    needs: run-build-ubuntu
+  # run-build-manylinux-aarch64:
+  #   runs-on: ubuntu-latest
+  #   needs: run-build-ubuntu
 
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+  #   steps:
+  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 
-      - name: Check out repository code
-        uses: actions/checkout@v3
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-        with:
-          platforms: arm64
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v2
+  #       with:
+  #         platforms: arm64
   
-      - name: Build
-        run: ./docker/linux-arm/deploy.sh
+  #     - name: Build
+  #       run: ./docker/linux-arm/deploy.sh
     
-      - name: Save artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: build-output-ubuntu-arm64
-          retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
-          path: |
-            *.gz
+  #     - name: Save artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: build-output-ubuntu-arm64
+  #         retention-days: ${{ github.event_name == 'pull_request' && 3 || 90 }}
+  #         path: |
+  #           *.gz
     
-      - run: echo "🐧 This job's status is ${{ job.status }}."
+  #     - run: echo "🐧 This job's status is ${{ job.status }}."
 
   # run-build-windows:
   #   runs-on: windows-2019
@@ -307,79 +307,79 @@ jobs:
 
   #     - run: echo "This job's status is ${{ job.status }}."
 
-  test-with-quickstart:
-    needs: run-build-ubuntu
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-java@v3
-        with:
-          # See https://github.com/actions/setup-java#supported-distributions for list
-          distribution: 'temurin'
-          java-version: '11.0.22+7'
+  # test-with-quickstart:
+  #   needs: run-build-ubuntu
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-java@v3
+  #       with:
+  #         # See https://github.com/actions/setup-java#supported-distributions for list
+  #         distribution: 'temurin'
+  #         java-version: '11.0.22+7'
 
-      - name: Download artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: build-output-ubuntu
+  #     - name: Download artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: build-output-ubuntu
 
-      - name: Untar artifact
-        run: |
-          tar -xzvf *.tar.gz
+  #     - name: Untar artifact
+  #       run: |
+  #         tar -xzvf *.tar.gz
 
-      - name: Git clone opentdf 
-        run: |
-          git clone --depth 1 https://github.com/opentdf/opentdf.git
+  #     - name: Git clone opentdf 
+  #       run: |
+  #         git clone --depth 1 https://github.com/opentdf/opentdf.git
 
-      - uses: yokawasa/action-setup-kube-tools@v0.9.2
-        with:
-          setup-tools: |
-            kubectl
-            helm
-            tilt
-          # This should be in sync with the minikube-deployed kube version below
-          kubectl: "1.24.1"
-          helm: "3.9.1"
-          tilt: "0.30.4"
+  #     - uses: yokawasa/action-setup-kube-tools@v0.9.2
+  #       with:
+  #         setup-tools: |
+  #           kubectl
+  #           helm
+  #           tilt
+  #         # This should be in sync with the minikube-deployed kube version below
+  #         kubectl: "1.24.1"
+  #         helm: "3.9.1"
+  #         tilt: "0.30.4"
 
-      - run: |
-          kubectl version --client
-          kustomize version
-          tilt version
+  #     - run: |
+  #         kubectl version --client
+  #         kustomize version
+  #         tilt version
 
-      - name: start minikube
-        id: minikube
-        uses: medyagh/setup-minikube@master
-        with:
-          minikube-version: 1.26.0
-          # This should be in sync with the setup-tools version above
-          kubernetes-version: 1.24.1
+  #     - name: start minikube
+  #       id: minikube
+  #       uses: medyagh/setup-minikube@master
+  #       with:
+  #         minikube-version: 1.26.0
+  #         # This should be in sync with the setup-tools version above
+  #         kubernetes-version: 1.24.1
 
-      - name: Run tilt & run sanity test
-        env:
-          # This test script is passed to opentdf/quickstart tilt file
-          TEST_SCRIPT: ../../wait-and-test.sh
-        run: |-
-          kubectl version
-          pwd
-          cd opentdf/quickstart
-          pwd
-          tilt ci
+  #     - name: Run tilt & run sanity test
+  #       env:
+  #         # This test script is passed to opentdf/quickstart tilt file
+  #         TEST_SCRIPT: ../../wait-and-test.sh
+  #       run: |-
+  #         kubectl version
+  #         pwd
+  #         cd opentdf/quickstart
+  #         pwd
+  #         tilt ci
 
-  ci:
-    needs:
-      - run-build-ubuntu
-      - test-with-quickstart
-      - run-build-manylinux-aarch64
-      # - run-build-mac
-      # - run-build-windows
-      # - run-build-multi
-      # - run-build-m1
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1
-        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+  # ci:
+  #   needs:
+  #     - run-build-ubuntu
+  #     - test-with-quickstart
+  #     - run-build-manylinux-aarch64
+  #     # - run-build-mac
+  #     # - run-build-windows
+  #     # - run-build-multi
+  #     # - run-build-m1
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: exit 1
+  #       if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
 
   # check-version-published:
   #   needs: ci
@@ -389,6 +389,9 @@ jobs:
   #     version-published: ${{ steps.versions.outputs.latest }}
   #     current-version: ${{ steps.versions.outputs.current }}
   #   steps:
+  #     - name: Set env
+  #       run: |-
+  #        echo "VERSION=${{ needs.set-release-version.outputs.package-version }}" >> $GITHUB_ENV
   #     - id: versions
   #       run: |-
   #         echo "latest=$(gh api -H "Accept: application/vnd.github+json" \
@@ -406,17 +409,21 @@ jobs:
   #   outputs:
   #     package-version: ${{ steps.versions.outputs.use-version }}
   #   steps:
+  #     - name: Set env
+  #       run: |-
+  #        echo "VERSION=${{ needs.set-release-version.outputs.package-version }}" >> $GITHUB_ENV
+  #        echo "SHORTSHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
   #     - id: decide-version
   #       run: |-
   #         if [[ "${{ needs.check-version-published.outputs.version-published }}" == "${{ needs.check-version-published.outputs.current-version }}" ]]; then
-  #           echo "use-version=$VERSION-SNAPSHOT" >> $GITHUB_OUTPUT"
+  #           echo "use-version=$VERSION-$SHORTSHA-SNAPSHOT" >> $GITHUB_OUTPUT"
   #         else
   #           echo "use-version=$VERSION" >> $GITHUB_OUTPUT"
   #         fi
 
 
   run-publish-linux:
-    needs: [ci]
+    # needs: [ci]
     # needs: [set-release-version]
     runs-on: ubuntu-latest
     # if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'schedule') }}
@@ -433,16 +440,17 @@ jobs:
         #echo "VERSION=${{ needs.set-release-version.outputs.package-version }}" >> $GITHUB_ENV
 
       - name: Download linux amd64 artifact
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: build-output-ubuntu
+          run-id: 7708430175
 
       - name: Untar linux amd64 artifact
         run: |
           tar -xzvf tdf-lib-java.tar.gz
       
       - name: Publish amd64 package
-        run: mvn --batch-mode deploy:deploy-file -s multi/settings.xml \
+        run: mvn --batch-mode deploy:deploy-file -e -s multi/settings.xml \
           -DrepositoryId=github \
           -Durl=https://maven.pkg.github.com/opentdf/client-java \
           -Dfile=tdf-lib-java/tdf-sdk-linux_64-${{ env.VERSION }}.jar \
@@ -461,9 +469,10 @@ jobs:
           rm -rf tdf-lib-java tdf-lib-java.tar.gz
 
       - name: Download linux arm64 artifact
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: build-output-ubuntu-arm64
+          run-id: 7708430175
 
       - name: Untar linux arm64 artifact
         run: |
@@ -471,7 +480,8 @@ jobs:
 
       - name: Publish arm64 package
         if: github.ref == 'refs/heads/main' && github.event_name != 'schedule'
-        run: mvn --batch-mode deploy:deploy-file -s multi/settings.xml \
+        run: |
+          mvn --batch-mode deploy:deploy-file -s multi/settings.xml \
           -DrepositoryId=github \
           -Durl=https://maven.pkg.github.com/opentdf/client-java \
           -Dfile=tdf-lib-java/tdf-sdk-linux_64-${{ env.VERSION }}.jar \
@@ -481,6 +491,9 @@ jobs:
           -Dpackaging=jar \
           -DgeneratePom=true \
           -Dclassifier=arm64
+        env:
+          USERNAME: ${{ github.actor }}
+          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
 
   # run-publish-mac:
   #   needs: [set-release-version]
@@ -546,6 +559,9 @@ jobs:
   #     #     -Dpackaging=jar \
   #     #     -DgeneratePom=true \
   #     #     -Dclassifier=arm64
+          # env:
+          # USERNAME: ${{ github.actor }}
+          # PASSWORD: ${{ secrets.GITHUB_TOKEN }}
 
   # run-publish-multi:
   #   needs: [set-release-version]
